excluded:
  - Pods

disabled_rules:
  - cyclomatic_complexity
  - type_name
  - force_cast
  - trailing_whitespace
  - todo
  - variable_name
  - force_try
  - unused_optional_binding
  - file_length
  - function_body_length
  - type_body_length
  - line_length

line_length: 120
